
const lang = {
    en: {
        search: "Search",
        gptSearchPlaceholder: "What you would like to watch today?",
        homePage: "Home Page",
        gptSearch: "GPT Search",
        nowPlaying: "Now Playing",
        topRated: "Top Rated",
        popular: "Popular",
        upcoming: "Upcoming",
        play: "Play",
        moreInfo: "More Info",
        signOut: "Sign Out",
        signIn: "Sign In",
        signUp: "Sign Up",
        now: "now",
        email: "Email",
        password: "Password",
        fullName: "Full Name",
        confirm: "Confirm",
        newToNetflix: "New to Netflix",
        alreadyRegistered: "Already registered",
        suggestion: "AI Suggestions",
    },
    hindi: {
        search: "खोजें",
        gptSearchPlaceholder: "आज आप क्या देखना पसंद करेंगे?",
        homePage: "होम पेज",
        gptSearch: "जी.पी.टी से खोजें",
        nowPlaying: "अभी चल रही",
        topRated: "सर्वोच्च रेटिंग",
        popular: "लोकप्रिय",
        upcoming: "आगामी",
        play: "चलायें ",
        moreInfo: "अधिक जानकारी",
        signOut: "साइन आउट",
        signIn: "साइन इन",
        signUp: "साइन अप",
        now: "अभी",
        email: "ईमेल",
        password: "पासवर्ड",
        fullName: "पूरा नाम",
        confirm: "पुष्टि करें",
        newToNetflix: "नेटफ्लिक्स पर नए हैं",
        alreadyRegistered: "पहले से ही पंजीकृत",
        suggestion: "ए.आई. के सुझाव",
    },
    russian: {
        search: "Поиск",
        gptSearchPlaceholder: "Что бы вы хотели увидеть сегодня?",
        homePage: "Домашняя страница",
        gptSearch: "Поиск из GPT",
        nowPlaying: "Сейчас воспроизводятся",
        topRated: "самые рейтинговые",
        popular: "популярный",
        upcoming: "предстоящий",
        play: "Играть",
        moreInfo: "Дополнительная информация",
        signOut: "выход",
        signIn: "войти",
        signUp: "зарегистрироваться",
        now: "Сейчас!",
        email: "электронная почта",
        password: "пароль",
        fullName: "полное имя",
        confirm: "Подтверждать",
        newToNetflix: "новичок в netflix",
        alreadyRegistered: "уже зарегистрирован",
        suggestion: "предложения ИИ",
    },
};

export default lang;